name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Fetch dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt install -y clinfo ocl-icd-opencl-dev pocl-opencl-icd
        clinfo

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: master

    - name: Check formatting
      run: zig fmt --check .

    - name: Test examples
      run: zig build --build-file $(pwd)/examples/build.zig test

